stages:
  - build
  - deploy
  

#
# BUILD
#

.build_app_base:
  stage: build
  image: node:16-alpine
  artifacts:
    paths:
      - nest_desktop
    variables:
      - VERSION
  before_script:
    - VERSION=`node -p "require('./package.json').version"`
  script:
    - yarn install
    - yarn build
  tags:
    - docker-runner


build_app_dev:
  extends: .build_app_base
  rules:
    - if: $CI_COMMIT_BRANCH == "gitlab-ci"
  before_script:
    - VERSION=`node -p "require('./package.json').version"`
    - echo '__version__ = "'${VERSION}dev${CI_PIPELINE_IID}'"' >> nest_desktop/__init__.py    
    
build_app_prod:
  extends: .build_app_base
  rules:
    - if: $CI_COMMIT_BRANCH == "main"


#
# DEPLOY PYTHON PACKAGE
#

.deploy_pip_base:
  stage: deploy
  image: python:latest
  before_script:
    - pip install twine
    - python setup.py sdist bdist_wheel
  tags:
    - docker-runner

deploy_testpypi:
  extends: .deploy_pip_base  
  needs:
    - build_app_dev
  rules:
    - if: $CI_COMMIT_BRANCH == "gitlab-ci"
      when: manual
  script:
    - TWINE_PASSWORD=${TESTPYPI_ACCESS_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository testpypi dist/*

deploy_pypi:
  extends: .deploy_pip_base  
  needs:
    - build_app_prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  script:
    - TWINE_PASSWORD=${PYPI_ACCESS_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*


#
# DEPLOY DOCKER IMAGE
#

.deploy_ebrains_docker_base:
  stage: deploy
  image: ubuntu:20.04
  before_script:
    - docker login -u $EBRAINS_DOCKER_REGISTRY_USER -p $EBRAINS_DOCKER_REGISTRY_TOKEN docker-registry.ebrains.eu
  tags:
    - shell-runner

deploy_ebrains_docker_dev:
  extends: .deploy_ebrains_docker_base
  needs:
    - build_app_dev
  rules:
    - if: $CI_COMMIT_BRANCH == "gitlab-ci"
  script:
    - docker build -f .gitlab-ci-docker/Dockerfile -t docker-registry.ebrains.eu/nest/nest-desktop:$VERSIONdev$CI_PIPELINE_IID .
    - docker push docker-registry.ebrains.eu/nest/nest-desktop:$VERSIONdev$CI_PIPELINE_IID

deploy_ebrains_docker:
  extends: .deploy_ebrains_docker_base
  needs:
    - build_app_prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - docker build -f .gitlab-ci-docker/Dockerfile -t docker-registry.ebrains.eu/nest/nest-desktop:$VERSION .
    - docker push docker-registry.ebrains.eu/nest/nest-desktop:$VERSION
