version: '3'

services:
  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:3.1
    environment:
      NEST_SIMULATOR_PORT: 52425
    ports:
      - '8000:8000'

  nest-simulator:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.3
    environment:
      NEST_CONTAINER_MODE: 'nest-server'
    ports:
      - '5000:5000'
