---
kind: Template
apiVersion: v1
metadata:
  name: nest-desktop
labels:
  template: nest-desktop
  app: nest-desktop
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: nest-desktop
  data:
    nest-server.json: |-
      {
        "host": "bnn20.apps.hbp.eu/server",
        "port": "",
        "secure": true
      }
